### ISSUE TITLE
Add support for laravel 8.0

### ISSUE THREAD

**Issue by hinimajesty** [shetabit/tokenable#2]
Composer tells me this when i try to install it within laravel 8. 

  Problem 1
    - Root composer.json requires shetabit/token-builder ^1.1 -> satisfiable by shetabit/token-builder[v1.1].
    - shetabit/token-builder v1.1 requires illuminate/support ^5.8|6.*|7.* -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.

**Comment by sifex** [comment]
@hinimajesty This is completed in #3 :)

**Comment by khanzadimahdi** [comment]
please fix it and create a new merge request.

**Comment by tanvirnexus** [comment]
Fetching the same problem.

**Comment by sifex** [comment]
Hey @everyone, as there is no available release for a while now, use the `dev-master` release if you wish to use the VCS version, though as always, disclaimer to never use the VCS version whenever possible:
https://stackoverflow.com/a/19009641/15375077

@shetabit Can you please craft a new GH release?

**Comment by khanzadimahdi** [comment]
please fix it and create a pull request

**Comment by khanzadimahdi** [comment]
install the new release.

https://github.com/shetabit/token-builder/releases/tag/v1.2

it must be fixed.
