### ISSUE TITLE
Can't install in Laravel9

### ISSUE THREAD

**Issue by tanvirnexus** [shetabit/tokenable#4]
Getting following errors when trying to install it in laravel9

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires shetabit/token-builder ^1.1 -> satisfiable by shetabit/token-builder[v1.1].
    - shetabit/token-builder v1.1 requires illuminate/support ^5.8|6.*|7.* -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
```

**Comment by sifex** [comment]
Can find _a_ solution here: https://github.com/shetabit/token-builder/issues/2#issuecomment-1057945694

**Comment by khanzadimahdi** [comment]
please fix it and create a pull request

**Comment by sifex** [comment]
Hey @khanzadimahdi this is already fixed, please tag a release. 

Please also do a little bit more investigation before commenting that, as it can seem dismissive and actually discourages discussions and contributions 😊

**Comment by khanzadimahdi** [comment]
@sifex sorry for that. the new release is ready.

https://github.com/shetabit/token-builder/releases/tag/v1.2
